install_requirements:
	npm install --global --update webpack babel-cli webpack-dev-server
	npm install

compile:
	webpack

compile_watch:
	webpack --watch

webpack_server:
	webpack-dev-server

open:
	open http://localhost:8080
